language: rust
sudo: false

dist: trusty
os:
  - linux

#run builds for all Rust versions.
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  global:
    - RUSTFLAGS="-C link-dead-code"

#For codecov
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev


# The main build
script:
  - cargo build --verbose
  - cargo test --all --verbose

#Code to run after build success
after_success: |
  [ $TRAVIS_RUST_VERSION = stable ] &&
  wget https://github.com/shaneutt/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make && make install DESTDIR=../tmp && cd ../.. &&
  ls target/debug &&
  ./kcov-master/tmp/usr/local/bin/kcov –coveralls-id=$TRAVIS_JOB_ID –exclude-pattern=/.cargo target/kcov target/debug/maskerad_object_pool-*
